// fullstack/generator/react/template/react_structure/src/components/PageNotFound/PageNotFound.tsx
import { useNavigate } from "react-router-dom";
import "./PageNotFound.scss";
import React from "react";

const PageNotFound: React.FC = () => {
  const navigate = useNavigate();

  const handleGoHomeClick = (): void => {
    navigate("/home");
  }

  return (
    <div className="position">
        <img src="/page-not-found.gif" alt="home" className="image"/>
        <h1>Ooops!</h1>
        <h3>It looks like you've gotten lost.</h3>

        <div className="homeButton">
            <div className="wrapper">
                <button className="button" onClick={handleGoHomeClick}>
                    <p className="label"> Go home </p>
                </button>
            </div>
        </div>
    </div>
  );
};

export default PageNotFound;

// fullstack/generator/angular/template/angular_structure/src/app/pages/page-not-found/page-not-found.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-page-not-found',
  templateUrl: './page-not-found.component.html',
  styleUrls: ['./page-not-found.component.scss'],
})
export class PageNotFoundComponent implements OnInit {
  constructor(private router: Router) {}

  ngOnInit(): void {}

  handleGoHomeClick(): void {
    this.router.navigate(['/home']);
  }
}

<div class="position">
    <img src='../../assets/image/page-not-found.gif' alt="home" class="image"/>
    <h1>Ooops!</h1>
    <h3>It looks like you've gotten lost.</h3>

    <div class="homeButton">
        <div class="wrapper">
            <button class="button" (click)="handleGoHomeClick()">
                <p class="label"> Go home </p>
            </button>
        </div>
    </div>
</div>
