// fullstack/generator/react/template/react_structure/src/components/ConfirmationDialog/ConfirmationDialog.tsx
import React from 'react';
import { Dialog, DialogActions, DialogTitle, Button } from '@mui/material';

interface ConfirmationDialogProps {
  open: boolean;
  onClose: (confirmed: boolean) => void;
}

const ConfirmationDialog: React.FC<ConfirmationDialogProps> = ({ open, onClose }) => {
  const handleCancel = () => {
    onClose(false);
  };

  const handleConfirm = () => {
    onClose(true);
  };

  return (
    <Dialog open={open} onClose={() => onClose(false)}>
      <div className="flex flex-col gap-y-4 px-10 py-4 rounded-xl">
        <DialogTitle>Are you sure you want to delete this?</DialogTitle>
        <DialogActions className="flex gap-x-4 items-center" align="center">
          <Button onClick={handleCancel} variant="outlined" color="primary" className="w-[8vw]">Cancel</Button>
          <Button onClick={handleConfirm} variant="contained" color="secondary" className="w-[8vw]">Delete</Button>
        </DialogActions>
      </div>
    </Dialog>
  );
};

export default ConfirmationDialog;

// fullstack/generator/angular/template/angular_structure/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
import { Component } from '@angular/core';
import { MatDialogRef } from '@angular/material/dialog';

@Component({
  selector: 'app-confirmation-dialog',
  templateUrl: './confirmation-dialog.component.html',
  styleUrls: ['./confirmation-dialog.component.scss'],
})
export class ConfirmationDialogComponent {
  constructor(public dialogRef: MatDialogRef<ConfirmationDialogComponent>) {}

  onCancelClick(): void {
    this.dialogRef.close(false);
  }

  onConfirmClick(): void {
    this.dialogRef.close(true);
  }
}

<div class="flex flex-col gap-y-4 px-10 py-4 rounded-xl">
  <h2 mat-dialog-title>Are you sure you want to delete this?</h2>

  <mat-dialog-actions align="center" class="flex gap-x-4 items-center">
    <button class="w-[8vw]" (click)="onCancelClick()">Cancel</button>
    <button class="w-[8vw]" (click)="onConfirmClick()">Delete</button>
  </mat-dialog-actions>
</div>
